### ISSUE TITLE
ERROR: nlopt failure

### ISSUE THREAD

**Issue by jeff-regier** [JuliaOpt/NLopt.jl#33] opened 2015-02-22 21:07 UTC
I often encounter "ERROR: nlopt failure" when I run NLopt with ftol_abs set to let less than 1e-6.  Is that behavior to be expected? I'd like to set ftol_abs to about 1e-8. The derivatives I pass to NLopt are all analytic, and I've verified them in test cases by comparing them to results from numeric differentiation. Are these errors likely due to numerical instability, i.e. slight incompatibilities between the objective function's values the derivatives? Or are there other common causes of nlopt failures? Are there any standard ways to work around this type of error?
Thanks.

**Comment by stevengj** [comment] 2015-02-24 17:40
Which algorithm are you using?

At some point, you will run into roundoff-error limitations, although in that case NLopt should ideally throw a "roundoff-limited" exception.

**Comment by jeff-regier** [comment] 2015-02-24 17:44
LD_LBFGS. I've never encountered a round off error, only "nlopt failure".

**Comment by stevengj** [comment] 2015-04-17 16:18
Do you have a simple test case that illustrates this?

**Comment by jeff-regier** [comment] 2015-04-17 17:40
I don't, unfortunately. I realize that makes it pretty difficult to diagnose the problem. The problem only appears for fairly complicated optimization problems. If I can recreate it without a lot of optimization variables, I'll post the code here.

**Comment by stevengj** [comment] 2015-04-17 17:57
See also stevengj/nlopt#28 (a vaguely similar issue with SLSQP, which I'm also having difficulty reproducing).

**Comment by danamm** [comment] 2015-05-07 00:57
Using NLopt (LD_LBFGS solver in Julia),  I am receiving nlopt failure error. I am suspicious that the options are not set properly.  I am wondering how to check that option parameters passed is actually set correctly?

I ask because I am setting fairly large values as below

    NLopt.ftol_abs!(opts, 0.1);
    NLopt.xtol_abs!(opts, 0.1);    
    NLopt.ftol_rel!(opts, 0.1);
    NLopt.xtol_rel!(opts, 0.1);
    NLopt.maxeval!(opts, 100);   
    NLopt.min_objective!(opts, fun);
    NLopt.lower_bounds!(opts, 0.0);
    obj, X, ret = NLopt.optimize(opts, X0)

But what I see is that, while objective is fixed up to 6 digits, solution up to 9 digits, and gradient is small (order of 1e-7 to 1e-15) the optimization does not stop, until it sends an

> nlopt failure Error

which there is no clue why the error happens.

**Comment by stevengj** [comment] 2015-05-12 16:23
If the options are incorrect it would through a different exception.   The BFGS failures are a bit harder to diagnose (in part because the Fortran BFGS code I am calling is rather opaque), but usually stem from you gradient not being accurate enough.    Do you have an analytical gradient?  If so, have you checked it against a finite-difference approximation?

**Comment by danamm** [comment] 2015-05-16 21:46
Yes, analytical gradients are used, and I have checked correctness against Calculus.gradient.

**Comment by jotwin** [comment] 2017-05-18 19:58
I'm getting this problem too in my complicated optimization. I'm using LBFGS and analytic gradients. I've never seen a roundoff error, only "nlopt failure -1". It goes away if I relax ftol_abs. Sorry I don't have a simple test case.

**Comment by reem21090** [comment] 2019-06-08 06:28
I am using NLOPT on G1 CEC test problem, I use the lower bounds as start points which are all in the feasible region. However, The error 

> nlopt.RoundoffLimited: NLopt roundoff-limited 

appears, but after running several times it may not appear but then appears again. 

It doesn't make the code predictable, so I wonder if its due to a bug in the nlopt library, please advise me how to get over it. Thanks

**Comment by mzaffalon** [comment] 2019-06-08 06:51
@reem21090 Can you provide a minimal working example of your code?

**Comment by reem21090** [comment] 2019-06-08 07:38
`import nlopt
from pymop.problems.g import G4
import random

def wrap_myfunc(x,grad):
    return problem.evaluate(x, return_values_of=["F"])[0]

def wrap_myconstraint(x, grad,i):
    return problem.evaluate(x, return_values_of=["G"])[i]

m=0
n_tests = 2
problem = G4()
nobj = problem.n_obj
ncon = problem.n_constr
nvar = problem.n_var
ub = problem.xu
lb = problem.xl
#init
while m<n_tests:
    print('iter', m)
    opt = nlopt.opt(nlopt.LD_SLSQP, nvar)
    opt.set_lower_bounds(lb)
    opt.set_upper_bounds(ub)
    opt.set_xtol_rel(1e-4)
    # x = symbols(['x{}'.format(i) for i in range(nvar)])
    opt.set_min_objective(wrap_myfunc)
    test_points = [0] * nvar
    for rand_n in range(nvar):
        print('rand_n', rand_n)
        # print('lb[rand_n]', lb[rand_n], 'ub[rand_n]', ub[rand_n])
        # ub_new=round(ub[rand_n]/20)
        test_points[rand_n] = random.randint(lb[rand_n], ub[rand_n])
    print('test_points', test_points)

    print('Gs',problem.evaluate(test_points, return_values_of=["G"]))
    CV = problem.evaluate(test_points, return_values_of=["CV"])
    print(type(CV),CV)
    if CV>0:
        print('using lower bound')
        x = opt.optimize(lb)
        print('lb', lb)
    else:
        print('using start points')
        x = opt.optimize(test_points)
        print('ub', ub)
    minf = opt.last_optimum_value()
    print("optimum at ", x)
    print("minimum value = ", minf)
    print("result code = ", opt.last_optimize_result())
    m=m+1

print('lb', lb, 'ub', ub)`

**Comment by liuliucen** [comment] 2020-06-22 07:44
Hi,
here is  my minimal working example code which always gives a roundoff error
i really don't know  how to solve it.
any suggestions?
[main.txt](https://github.com/JuliaOpt/NLopt.jl/files/4811862/main.txt)

**Comment by mayou36** [comment] 2021-02-24 20:07
So for me, I've got this error a lot when the initial points are _too close_ to the minimum. So I'll artificially set the somewhere else (e.g. by the `sqrt(inv_hessian)`

**Comment by odow** [comment] 2024-08-16 03:19
For examples like `nlopt failure -1`, with https://github.com/JuliaOpt/NLopt.jl/pull/221, we now return error results to the user which may be sufficient, or help diagnosing.

I'm going to close this issue because it is pretty old, non-specific, and because most of the comments are numerical issues that are specific to particular algorithms in the C library, not issues in the Julia wrapper.

**Closed by odow** 2024-08-16 03:19 UTC
