### ISSUE TITLE
NLopt installing error on Windows

### ISSUE THREAD

**Issue by cecileane** [JuliaOpt/NLopt.jl#53] opened 2016-03-17 21:46 UTC
When trying to install NLopt on Windows (64 bits Windows 7 Pro), I get this error below. 
I got basically the same error when trying `Pkg.build("NLopt")`.

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.add("NLopt")
INFO: Initializing package repository C:\Users\Cecile Ane\.julia\v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of MathProgBase from git://github.com/JuliaOpt/MathProgBase.
jl.git
INFO: Cloning cache of NLopt from git://github.com/JuliaOpt/NLopt.jl.git
INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git

INFO: Installing BinDeps v0.3.21
INFO: Installing Compat v0.7.12
INFO: Installing MathProgBase v0.4.2
INFO: Installing NLopt v0.3.1
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.3
INFO: Building NLopt
INFO: Attempting to Create directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\
downloads
INFO: Downloading file http://ab-initio.mit.edu/nlopt/nlopt-2.4.1-dll32.zip
INFO: Done downloading file http://ab-initio.mit.edu/nlopt/nlopt-2.4.1-dll32.zip

INFO: Attempting to Create directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\
downloads
INFO: Directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\downloads already cre
ated
INFO: Downloading file http://ab-initio.mit.edu/nlopt/nlopt-2.4.1-dll64.zip
INFO: Done downloading file http://ab-initio.mit.edu/nlopt/nlopt-2.4.1-dll64.zip

INFO: Attempting to Create directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\
src
INFO: Attempting to Create directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\
src\w32
INFO: Attempting to Create directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\
src\w64
INFO: Attempting to Create directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\
src
INFO: Directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\src already created

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\downloads\nlopt-2
.4.1-dll32.zip

Extracting  libnlopt-0.dll
Extracting  libnlopt-0.def
Extracting  nlopt.f
Extracting  nlopt.h
Extracting  nlopt.hpp
Extracting  nlopt.py
Extracting  nlopt-python.cpp
Extracting  setup.py
Extracting  README
Extracting  COPYING
Extracting  COPYRIGHT
Extracting  NEWS
Extracting  README-WINDOWS
Extracting  matlab\NLOPT_AUGLAG_EQ.m
Extracting  matlab\NLOPT_AUGLAG.m
Extracting  matlab\NLOPT_GD_MLSL_LDS.m
Extracting  matlab\NLOPT_GD_MLSL.m
Extracting  matlab\NLOPT_GD_STOGO.m
Extracting  matlab\NLOPT_GD_STOGO_RAND.m
Extracting  matlab\NLOPT_G_MLSL_LDS.m
Extracting  matlab\NLOPT_G_MLSL.m
Extracting  matlab\NLOPT_GN_CRS2_LM.m
Extracting  matlab\NLOPT_GN_DIRECT_L.m
Extracting  matlab\NLOPT_GN_DIRECT_L_NOSCAL.m
Extracting  matlab\NLOPT_GN_DIRECT_L_RAND.m
Extracting  matlab\NLOPT_GN_DIRECT_L_RAND_NOSCAL.m
Extracting  matlab\NLOPT_GN_DIRECT.m
Extracting  matlab\NLOPT_GN_DIRECT_NOSCAL.m
Extracting  matlab\NLOPT_GN_ESCH.m
Extracting  matlab\NLOPT_GN_ISRES.m
Extracting  matlab\NLOPT_GN_MLSL_LDS.m
Extracting  matlab\NLOPT_GN_MLSL.m
Extracting  matlab\NLOPT_GN_ORIG_DIRECT_L.m
Extracting  matlab\NLOPT_GN_ORIG_DIRECT.m
Extracting  matlab\NLOPT_LD_AUGLAG_EQ.m
Extracting  matlab\NLOPT_LD_AUGLAG.m
Extracting  matlab\NLOPT_LD_CCSAQ.m
Extracting  matlab\NLOPT_LD_LBFGS.m
Extracting  matlab\NLOPT_LD_LBFGS_NOCEDAL.m
Extracting  matlab\NLOPT_LD_MMA.m
Extracting  matlab\NLOPT_LD_SLSQP.m
Extracting  matlab\NLOPT_LD_TNEWTON.m
Extracting  matlab\NLOPT_LD_TNEWTON_PRECOND.m
Extracting  matlab\NLOPT_LD_TNEWTON_PRECOND_RESTART.m
Extracting  matlab\NLOPT_LD_TNEWTON_RESTART.m
Extracting  matlab\NLOPT_LD_VAR1.m
Extracting  matlab\NLOPT_LD_VAR2.m
Extracting  matlab\NLOPT_LN_AUGLAG_EQ.m
Extracting  matlab\NLOPT_LN_AUGLAG.m
Extracting  matlab\NLOPT_LN_BOBYQA.m
Extracting  matlab\NLOPT_LN_COBYLA.m
Extracting  matlab\NLOPT_LN_NELDERMEAD.m
Extracting  matlab\NLOPT_LN_NEWUOA_BOUND.m
Extracting  matlab\NLOPT_LN_NEWUOA.m
Extracting  matlab\NLOPT_LN_PRAXIS.m
Extracting  matlab\NLOPT_LN_SBPLX.m
Extracting  matlab\nlopt_minimize_constrained.m
Extracting  matlab\nlopt_minimize.m
Extracting  matlab\nlopt_optimize.c
Extracting  matlab\nlopt_optimize.m

Everything is Ok

Files: 60
Size:       1602081
Compressed: 495108
INFO: Attempting to Create directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\
src
INFO: Directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\src already created

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\downloads\nlopt-2
.4.1-dll64.zip

Extracting  libnlopt-0.dll
Extracting  libnlopt-0.def
Extracting  nlopt.f
Extracting  nlopt.h
Extracting  nlopt.hpp
Extracting  nlopt.py
Extracting  nlopt-python.cpp
Extracting  setup.py
Extracting  README
Extracting  COPYING
Extracting  COPYRIGHT
Extracting  NEWS
Extracting  README-WINDOWS
Extracting  matlab\NLOPT_AUGLAG_EQ.m
Extracting  matlab\NLOPT_AUGLAG.m
Extracting  matlab\NLOPT_GD_MLSL_LDS.m
Extracting  matlab\NLOPT_GD_MLSL.m
Extracting  matlab\NLOPT_GD_STOGO.m
Extracting  matlab\NLOPT_GD_STOGO_RAND.m
Extracting  matlab\NLOPT_G_MLSL_LDS.m
Extracting  matlab\NLOPT_G_MLSL.m
Extracting  matlab\NLOPT_GN_CRS2_LM.m
Extracting  matlab\NLOPT_GN_DIRECT_L.m
Extracting  matlab\NLOPT_GN_DIRECT_L_NOSCAL.m
Extracting  matlab\NLOPT_GN_DIRECT_L_RAND.m
Extracting  matlab\NLOPT_GN_DIRECT_L_RAND_NOSCAL.m
Extracting  matlab\NLOPT_GN_DIRECT.m
Extracting  matlab\NLOPT_GN_DIRECT_NOSCAL.m
Extracting  matlab\NLOPT_GN_ESCH.m
Extracting  matlab\NLOPT_GN_ISRES.m
Extracting  matlab\NLOPT_GN_MLSL_LDS.m
Extracting  matlab\NLOPT_GN_MLSL.m
Extracting  matlab\NLOPT_GN_ORIG_DIRECT_L.m
Extracting  matlab\NLOPT_GN_ORIG_DIRECT.m
Extracting  matlab\NLOPT_LD_AUGLAG_EQ.m
Extracting  matlab\NLOPT_LD_AUGLAG.m
Extracting  matlab\NLOPT_LD_CCSAQ.m
Extracting  matlab\NLOPT_LD_LBFGS.m
Extracting  matlab\NLOPT_LD_LBFGS_NOCEDAL.m
Extracting  matlab\NLOPT_LD_MMA.m
Extracting  matlab\NLOPT_LD_SLSQP.m
Extracting  matlab\NLOPT_LD_TNEWTON.m
Extracting  matlab\NLOPT_LD_TNEWTON_PRECOND.m
Extracting  matlab\NLOPT_LD_TNEWTON_PRECOND_RESTART.m
Extracting  matlab\NLOPT_LD_TNEWTON_RESTART.m
Extracting  matlab\NLOPT_LD_VAR1.m
Extracting  matlab\NLOPT_LD_VAR2.m
Extracting  matlab\NLOPT_LN_AUGLAG_EQ.m
Extracting  matlab\NLOPT_LN_AUGLAG.m
Extracting  matlab\NLOPT_LN_BOBYQA.m
Extracting  matlab\NLOPT_LN_COBYLA.m
Extracting  matlab\NLOPT_LN_NELDERMEAD.m
Extracting  matlab\NLOPT_LN_NEWUOA_BOUND.m
Extracting  matlab\NLOPT_LN_NEWUOA.m
Extracting  matlab\NLOPT_LN_PRAXIS.m
Extracting  matlab\NLOPT_LN_SBPLX.m
Extracting  matlab\nlopt_minimize_constrained.m
Extracting  matlab\nlopt_minimize.m
Extracting  matlab\nlopt_optimize.c
Extracting  matlab\nlopt_optimize.m

Everything is Ok

Files: 60
Size:       1932764
Compressed: 541555
INFO: Attempting to Create directory C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\
usr\lib
INFO: Changing Directory to C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\src\w32
Copy-Item : A positional parameter cannot be found that accepts argument 'Ane\.
julia\v0.4\NLopt\deps\usr\lib\libnlopt32.dll'.
At line:1 char:3
+ cp <<<<  libnlopt-0.dll C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\usr\lib\li
bnlopt32.dll
    + CategoryInfo          : InvalidArgument: (:) [Copy-Item], ParameterBindi
   ngException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell
   .Commands.CopyItemCommand

================================[ ERROR: NLopt ]================================


LoadError: failed process: Process(`powershell -Command 'cp libnlopt-0.dll C:\Us
ers\Cecile Ane\.julia\v0.4\NLopt\deps\usr\lib\libnlopt32.dll'`, ProcessExited(1)
) [1]
while loading C:\Users\Cecile Ane\.julia\v0.4\NLopt\deps\build.jl, in expression
 starting on line 54

================================================================================


================================[ BUILD ERRORS ]================================


WARNING: NLopt had build errors.

 - packages with build errors remain installed in C:\Users\Cecile Ane\.julia\v0.
4
 - build the package(s) and all dependencies with `Pkg.build("NLopt")`
 - build a single package by running its `deps/build.jl` script

================================================================================

INFO: Package database updated
```

**Comment by mlubin** [comment] 2016-03-17 22:07
Looks like an issue with having a space in the directory name.

**Comment by cecileane** [comment] 2016-03-28 18:05
yeap, that was it. Thanks!

**Comment by mlubin** [comment] 2016-03-29 14:51
Let's leave this open because it's a bug in the build script

**Comment by stevengj** [comment] 2016-03-29 17:35
Line 54 of `build.jl` is just `@BinDeps.install Dict(:libnlopt => :libnlopt)`, so possibly the problem is in BinDeps?

**Comment by mlubin** [comment] 2016-03-29 17:37
The error is higher up, looks like it's related to https://github.com/JuliaOpt/NLopt.jl/commit/9cfb390de728092a2b751c23dd680aba6b0e60c4, CC @tkelman

**Comment by tkelman** [comment] 2016-03-29 17:58
2 options. Either add a few escaped quotes around the destination in that cp command, or repackage the binaries so they're contained in a subdirectory inside the zip file so we could revisit https://github.com/JuliaOpt/NLopt.jl/pull/49

**Comment by stevengj** [comment] 2016-08-18 17:31
Seems better to just call `cp` directly than do `powershell -Command "cp ..."`; should be fixed now, I hope.

**Comment by stevengj** [comment] 2016-08-18 17:36
Oh, fudge, I screwed it up.  I hate bindeps syntax.

**Closed** 2016-08-18 17:49 UTC

**Comment by stevengj** [comment] 2016-08-18 18:10
Okay, looks like it is working now.
