### ISSUE TITLE
Can not run test example in Julia 

### ISSUE THREAD

**Issue by ChrisNabold** [JuliaOpt/NLopt.jl#149] opened 2020-08-03 14:46 UTC
I added NLopt to my Julia 1.5 installation. Pkg.add a well using finishing without error message. However the test examples dont run.
In both myfunc and myconstraint the ::Vector is not acceptedthe lines inequality.constraint are also not accepted by Julia.
My be you can help.
Thank you and best regards
Chris

**Comment by mzaffalon** [comment] 2020-08-03 18:55
Can you please post the code you tried? See also https://discourse.julialang.org/t/psa-make-it-easier-to-help-you/14757

**Comment by IgnacioRubioScola** [comment] 2020-09-02 20:27
Hi,

I am using Julia 1.5.1 with:
[4076af6c] JuMP v0.21.3
[76087f3c] NLopt v0.6.0

`using JuMP
using NLopt

m = Model(solver=NLoptSolver(algorithm=:LD_MMA))

a1 = 2
b1 = 0
a2 = -1
b2 = 1

@variable(m, x1)
@variable(m, x2 >= 0)

@NLobjective(m, Min, sqrt(x2))
@NLconstraint(m, x2 >= (a1*x1+b1)^3)
@NLconstraint(m, x2 >= (a2*x1+b2)^3)

setvalue(x1, 1.234)
setvalue(x2, 5.678)

status = solve(m)

println("got ", getobjectivevalue(m), " at ", [getvalue(x1),getvalue(x2)])`

and I got the following error:
ERRROR: LoadError: The solver= keyword is no longer available in JuMP 0.19 and later. See the JuMP documentation (http://jump.dev/JuMP.jl/latest/) for latest syntax.

**Comment by stevengj** [comment] 2020-09-03 15:59
I just tried it, and the [tutorial code](https://github.com/JuliaOpt/NLopt.jl#tutorial) works fine for me in Julia 1.5 with a fresh install of NLopt.

**Comment by LaszloHars** [comment] 2020-10-26 21:38
I also tried the tutorial code. Only 2 gradient-using algorithms work: LD_MMA, and LD_SLSQP.

The other 7 algorithms of the NLopt library (LD_LBFGS, LD_TNEWTON - all 4 variants, LD_VAR1, LD_VAR2) all give the error at the first call of inequality_constraint!(...) :
LoadError: ArgumentError: invalid NLopt arguments: invalid algorithm for constraints

The documentation does not tell, what the problem is, and how to get around it. Can anyone help?

**Comment by mzaffalon** [comment] 2020-10-27 19:03
It is mentioned in https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#local-gradient-based-optimization.

**Comment by mx-the-gray** [comment] 2020-12-13 14:59
Hello
I installed JUliaPro Version : 1.5.3-1 (https://juliacomputing.com/products/juliapro/#curated-pkgs) in Windows10, I then installed NLopt with the Pkg command. All good. Note that I can use most of the packages I tested so far. I then tried to run the example here below but it gives me the following error:
---
ERROR: MethodError: objects of type Opt are not callable
Stacktrace:
 [1] value!!(::NonDifferentiable{Float64,Array{Float64,1}}, ::Array{Float64,1}) at C:\Users\MAX\.julia\packages\NLSolversBase\QPnui\src\interface.jl:9
 [2] initial_state(::NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}, ::Optim.Options{Float64,Nothing}, ::NonDifferentiable{Float64,Array{Float64,1}}, ::Array{Float64,1}) at C:\Users\MAX\.julia\packages\Optim\auGGa\src\multivariate\solvers\zeroth_order\nelder_mead.jl:158
 [3] optimize(::NonDifferentiable{Float64,Array{Float64,1}}, ::Array{Float64,1}, ::NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}, ::Optim.Options{Float64,Nothing}) at C:\Users\MAX\.julia\packages\Optim\auGGa\src\multivariate\optimize\optimize.jl:33     
 [4] optimize(::Opt, ::Array{Float64,1}; inplace::Bool, autodiff::Symbol, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\MAX\.julia\packages\Optim\auGGa\src\multivariate\optimize\interface.jl:90
 [5] optimize(::Opt, ::Array{Float64,1}) at C:\Users\MAX\.julia\packages\Optim\auGGa\src\multivariate\optimize\interface.jl:84       
 [6] top-level scope at none:1
----
using NLopt

function myfunc(x::Vector, grad::Vector)
    if length(grad) > 0
        grad[1] = 0
        grad[2] = 0.5/sqrt(x[2])
    end
    return sqrt(x[2])
end

function myconstraint(x::Vector, grad::Vector, a, b)
    if length(grad) > 0
        grad[1] = 3a * (a*x[1] + b)^2
        grad[2] = -1
    end
    (a*x[1] + b)^3 - x[2]
end

opt = Opt(:LD_MMA, 2)
opt.lower_bounds = [-Inf, 0.]
opt.xtol_rel = 1e-4

opt.min_objective = myfunc
inequality_constraint!(opt, (x,g) -> myconstraint(x,g,2,0), 1e-8)
inequality_constraint!(opt, (x,g) -> myconstraint(x,g,-1,1), 1e-8)

(minf,minx,ret) = optimize(opt, [1.234, 5.678])

**Comment by mzaffalon** [comment] 2020-12-13 15:35
What happens if you execute the code right after starting Julia again? Stacktrace [5] mentions `Optim`, but `NLopt` does not depend on this package. Can it be that you you used `Optim` just before trying this example?

**Comment by mx-the-gray** [comment] 2020-12-13 16:01
I did try a bunch of packages before this example, including Optim. Let me try to restart. Just to be clear. Does this mean that running NLopt is incompatible with using Optim?

**Comment by mx-the-gray** [comment] 2020-12-13 16:11
No error now but it performs only one iteration and exits with 
(2.382855429941145, [1.234, 5.678], :FORCED_STOP)

**Comment by LaszloHars** [comment] 2020-12-13 17:19
The variable "ax" does not exist. If you mean multiplication, use "a*x"
It is an unfortunate implementation decision in the NLopt Julia package, that a runtime error in the constraint function causes :FORCED_STOP, instead of giving a decent error message. I always use a dummy call of the objective function and the constraints before the actual optimization, just to catch trivial coding errors.

**Comment by mx-the-gray** [comment] 2020-12-13 23:35
Thanks, I just copied an pasted the example without checking. I am still learning. I started programming in Julia yesterday afternoon but it is really simple. I have already implemented a working DE.

**Comment by odow** [comment] 2022-03-03 01:56
Closing as non-reproducible:
```Julia
julia> using NLopt

julia> function myfunc(x::Vector, grad::Vector)
       if length(grad) > 0
       grad[1] = 0
       grad[2] = 0.5/sqrt(x[2])
       end
       return sqrt(x[2])
       end
myfunc (generic function with 1 method)

julia> function myconstraint(x::Vector, grad::Vector, a, b)
       if length(grad) > 0
       grad[1] = 3a * (a * x[1] + b)^2
       grad[2] = -1
       end
       (a * x[1] + b)^3 - x[2]
       end
myconstraint (generic function with 1 method)

julia> opt = Opt(:LD_MMA, 2)
Opt(LD_MMA, 2)

julia> opt.lower_bounds = [-Inf, 0.]
2-element Vector{Float64}:
 -Inf
   0.0

julia> opt.xtol_rel = 1e-4
0.0001

julia> opt.min_objective = myfunc
myfunc (generic function with 1 method)

julia> inequality_constraint!(opt, (x,g) -> myconstraint(x,g,2,0), 1e-8)

julia> inequality_constraint!(opt, (x,g) -> myconstraint(x,g,-1,1), 1e-8)

julia> (minf,minx,ret) = optimize(opt, [1.234, 5.678])
(0.5443310477213124, [0.3333333342139688, 0.29629628951338166], :XTOL_REACHED)
```
The ` optimize(::Opt, ::Array{Float64,1}) at C:\Users\MAX.julia\packages\Optim\auGGa\src\multivariate\optimize\interface.jl:84` suggests the user was calling `Optimization.optimize` instead of `NLopt.optimize`.

If anyone has follow-up questions to this thread, please post on the community forum, https://discourse.julialang.org/c/domain/opt/13, and tag me `@odow`.

**Closed by odow** 2022-03-03 01:56 UTC
