### ISSUE TITLE
issue with pmap: document?

### ISSUE THREAD

**Issue by cecileane** [JuliaOpt/NLopt.jl#146] opened 2020-05-20 23:12 UTC
This issue seems related to #12, but here is an example. The NLopt object is part of a type, to be reused multiple times. All is well, unless we want to distributed the work across processors.
```julia
using NLopt

struct Foo
  data::Vector{Float64}
  guess::Vector{Float64}
  opt::NLopt.Opt
end
function Foo(data, frel,fabs,maxeval)
  guess = similar(data)
  opt = NLopt.Opt(:LD_SLSQP, 1)
  NLopt.ftol_rel!(opt,frel)
  NLopt.ftol_abs!(opt,fabs)
  NLopt.maxeval!(opt, maxeval)
  return Foo(data,guess,opt)
end

foo = Foo([4.0,1.0,-5.0], .01,.01,5)

function optimizeone!(obj::Foo,i)
    function f(x, g)
        d = (x[1]-obj.data[i])
        objective = d*d
        if length(g) > 0
            g[1] = 2d
        end
        return objective
    end
    opt = foo.opt
    min_objective!(opt, f)
    optf, optx, ret = NLopt.optimize(opt, [obj.guess[i]])
    obj.guess[i] = optx[1]
    return obj.guess[i]
end

for i in 1:3
  optimizeone!(foo,i)
end
foo.guess ≈ foo.data # true
```

so all is well here. The problem appears when we use multiple processors:

```julia
foo = Foo([4.0,1.0,-5.0], .01,.01,5)
using Distributed
addprocs(1) # 1 worker
@everywhere using NLopt
bar = Distributed.pmap(1:3) do i
  optimizeone!(foo,i)
end
```

I get an error starting with:
```
ERROR: On worker 2:
UndefVarError: #optimizeone! not defined
deserialize_datatype at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:1211
```

As said in #12, I can serialize the optimization parameters and create the `Opt` object by the worker. But still, it would be a nice feature to have, and if not, it would be nice to be documented.

**Comment by odow** [comment] 2020-05-21 14:13
The error is not related to NLopt. Here is the relevant section of the Julia manual: https://docs.julialang.org/en/v1/manual/parallel-computing/#code-availability-1

To avoid issues with serializing the `NLopt.Opt`, you probably want to construct it on each process.
```Julia
@everywhere function optimizeone!(i)
    foo = Foo([4.0,1.0,-5.0], .01,.01,5)
    # ...
    return obj.guess
end
pmap(optimizeone!, 1:3)
```

**Comment by cecileane** [comment] 2020-05-21 14:36
Oh yes duh!! I am sorry, I read the error too fast. (it's an attempt to make a small example. In real life I'm running into this problem with things inside a module). So when I start julia with `julia -p 1`, say, and do `@everwhere` in front of almost everything above, the error is like this:
```
      From worker 2:	signal (11): Segmentation fault: 11
      From worker 2:	in expression starting at none:0
      From worker 2:	nlopt_get_errmsg at /Users/ane/.julia/artifacts/a98e645e32bc5ee2510d3fbf404e13941a7e2aa2/lib/libnlopt.0.10.0.dylib (unknown line)
      From worker 2:	errmsg at /Users/ane/.julia/packages/NLopt/KTzQh/src/NLopt.jl:198 [inlined]
      From worker 2:	_errmsg at /Users/ane/.julia/packages/NLopt/KTzQh/src/NLopt.jl:203
      From worker 2:	chk at /Users/ane/.julia/packages/NLopt/KTzQh/src/NLopt.jl:211
      From worker 2:	min_objective! at /Users/ane/.julia/packages/NLopt/KTzQh/src/NLopt.jl:406 [inlined]
      From worker 2:	optimizeone! at ./REPL[5]:11
      From worker 2:	#4 at ./REPL[9]:2
      From worker 2:	unknown function (ip: 0x109cc37a7)
      ...
```

To be replicate this:
```julia
@everywhere using NLopt

@everywhere struct Foo
  data::Vector{Float64}
  guess::Vector{Float64}
  opt::NLopt.Opt
end
@everywhere function Foo(data, frel,fabs,maxeval)
  guess = similar(data)
  opt = NLopt.Opt(:LD_SLSQP, 1)
  NLopt.ftol_rel!(opt,frel)
  NLopt.ftol_abs!(opt,fabs)
  NLopt.maxeval!(opt, maxeval)
  return Foo(data,guess,opt)
end
@everywhere function optimizeone!(obj::Foo,i)
    function f(x, g)
        d = (x[1]-obj.data[i])
        objective = d*d
        if length(g) > 0
            g[1] = 2d
        end
        return objective
    end
    opt = foo.opt
    min_objective!(opt, f)
    optf, optx, ret = NLopt.optimize(opt, [obj.guess[i]])
    obj.guess[i] = optx[1]
    return obj.guess[i]
end

foo = Foo([4.0,1.0,-5.0], .01,.01,5) # or @everywhere, same error
bar = Distributed.pmap(1:3) do i
  optimizeone!(foo,i)
end
```

```
(@v1.4) pkg> status
Status `~/.julia/environments/v1.4/Project.toml`
  [76087f3c] NLopt v0.6.0
```

**Comment by odow** [comment] 2020-05-21 14:43
You need to follow the second half of my previous comment.

**Comment by cecileane** [comment] 2020-05-21 15:50
oh yes, that's what I already did in my package. Documentation about the problem would have been helpful (and would have saved me time to diagnose the issue).

**Comment by odow** [comment] 2020-05-21 16:17
You can make a PR to improve the documentation by clicking on the pencil Icon at the top of the README on the homepage:
https://github.com/JuliaOpt/NLopt.jl/edit/master/README.md

**Comment by cecileane** [comment] 2020-05-21 21:48
yes! will do when I get the time.

**Comment by BioTurboNick** [comment] 2022-06-16 00:40
Ahh dangit. Burned myself with this one with `Threads.@spawn` multithreading.

I'd argue this is enough of a footgun that possibly NLopt.jl could try to detect if the same options object is being used simultaneously by multiple threads.

Could a flag be added to `struct Opt` that is set to `true` when accepted by `optimize` and `false` just before returning? And if the flag is already `true`, emit a warning or error? I suppose you'd also need a try/catch/finally to ensure it's reset to false even if there's an internal exception or interrupt.

**Comment by odow** [comment] 2023-01-25 00:58
Closing as a duplicate of https://github.com/JuliaOpt/NLopt.jl/issues/186.

**Closed by odow** 2023-01-25 00:58 UTC
